In [1]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
import numpy as np
import pandas as pd
from pprint import pprint
from os import listdir
from os.path import isfile, join
from sklearn.model_selection import StratifiedKFold
from scipy import stats
import numpy as np
from sklearn import linear_model, svm
import re
from sklearn.metrics import roc_curve, auc,f1_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
#s = "../braindata/data_1_mor_select_100.csv"
import os          
from sklearn import linear_model, svm
from sklearn.ensemble import ExtraTreesClassifier
import xgboost as xgb

print('finished this block')

finished this block


In [2]:
os.getcwd()
os.chdir('../data/adni')
print('finished this block')

finished this block


In [3]:
dd =pd.read_csv("combine_new_biomarker_correct.csv",header=0)
print('the original training data dimension is')
print(dd.shape)
import csv

the original training data dimension is
(179, 34733)


In [4]:
with open('combine_new_biomarker_correct.csv', 'r') as f:
    d_reader = csv.DictReader(f)
    #get fieldnames from DictReader object and store in list
    headers = d_reader.fieldnames
    
data=np.array(dd)

#idx_IN_columns = np.append(np.array([14,22]), np.array(range(23,data.shape[1])))
idx_IN_columns = np.array(range(1,6))

print(idx_IN_columns)

X=data[:,idx_IN_columns]
#X_biomarker=X[:,0:5]

y=data[:, 9]  
y_dxbl=data[:,10]

ind_num_matrix=np.isnan(X)
ind_num_vector=np.any(ind_num_matrix,axis=1)

X_no_nan=X[~ind_num_vector,:]
y_no_nan=y[~ind_num_vector]
y_dxbl_no_nan = y_dxbl[~ind_num_vector]

X=X_no_nan
y=y_no_nan
y_dxbl=y_dxbl_no_nan

MCI = (y_dxbl==2)
MCI_index =[ i for i in range(0, MCI.shape[0]) if MCI[i]]

print(X)
X = stats.zscore(X)

feature_num_all=[]

lr_all_feature=[]
svm_all_feature=[]
XGreg_all_feature=[]


lr_fls_feature=[]
svm_fls_feature=[]
XGB_f1s_feature=[]

base_labels= []


np.isnan(X).any()
X[np.isnan(X)] = np.median(X[~np.isnan(X)])

print("after the precoessing, the X.shape is ")
print(X.shape)
print("the y.shape is")
print(y.shape)
print("the number of MCI case is")
print(len(MCI_index))

[1 2 3 4 5]
[[ 168.           95.3          29.3           1.76285414    5.7337884 ]
 [ 234.           71.4          22.1           3.27731092   10.58823529]
 [ 241.           49.5          18.8           4.86868687   12.81914894]
 [ 130.           61.6          28.9           2.11038961    4.4982699 ]
 [ 136.          213.           76.            0.63849765    1.78947368]
 [ 142.           72.1          23.7           1.96948682    5.99156118]
 [ 170.           88.2          32.3           1.92743764    5.26315789]
 [ 204.           56.2          27.8           3.62989324    7.3381295 ]
 [ 106.          122.           66.1           0.86885246    1.60363086]
 [ 135.          116.           38.1           1.1637931     3.54330709]
 [ 147.           58.9          21.6           2.49575552    6.80555556]
 [ 185.           27.2          20.6           6.80147059    8.98058252]
 [ 140.           62.2          26.2           2.25080386    5.34351145]
 [ 142.           60.1          42.8   

In [6]:
sep1 = '*' * 100
sep2 = '*' * 50
sep3 = '*' * 30

print("beginning selection best number of features")

#this is the optimal feature
rbf = svm.SVC(C=100,kernel='linear')

accr_run  = []
f1s_run = []
accr_MCI_run= []
f1s_MCI_run = []    
    
base_labels=[]
    
for runs in range(10):
    counter=0
    print("\n RUN: {} {} \n".format(runs, sep3))
        
    accr_CV = []
    f1s_CV=[] 
    strat_labels = []
        
    test_labels_MCI_CV = []
    y_pred_MCI_CV = []
        
        
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=int(runs))
    for train_index, test_index in skf.split(X, y):       
        print("\n Fold: {} {} \n".format(counter, sep2))        
        counter=counter+1
                        
        train_data, test_data=X[train_index], X[test_index]
        train_labels, test_labels = y[train_index], y[test_index]
            
        strat_labels = np.append(strat_labels, test_labels)

            
        test_index_MCI = [test_index[i] for i in range(0, len(test_index)) if test_index[i] in MCI_index]
                                    
        #LR
            
        log = rbf.fit(train_data, train_labels)
        acc = rbf.score(test_data, test_labels)            
                
            #f1 calculation
        y_pred = rbf.predict(test_data)
        f1 = f1_score(test_labels, y_pred)
                                             
        print('Accuracy: %f' % acc)
        print('F1 score: %f' % f1)
                    
        accr_CV = np.append(accr_CV, acc)
        f1s_CV=np.append(f1s_CV, f1)             
            

        #MCI_case            
        if (len(test_index_MCI)==0):
            print("There is no MCI in this shuffling test set, so we skip it")
        else:
            test_data_MCI = X[test_index_MCI]
            test_labels_MCI = y[test_index_MCI]
            
            y_pred_MCI = rbf.predict(test_data_MCI)
                
            print(y_pred_MCI)
            print(test_labels_MCI)
                                    
            y_pred_MCI_CV = np.append(y_pred_MCI_CV, y_pred_MCI)
            test_labels_MCI_CV = np.append(test_labels_MCI_CV, test_labels_MCI)
                                                        
    base_labels=np.append(base_labels, strat_labels)  
        
    print("the mean accr_CV is")
    print(np.mean(accr_CV))
    print("the mean f1s_CV is")
    print(np.mean(f1s_CV))
    print("the accr_MCI_CV is")
    print(np.sum(test_labels_MCI_CV==y_pred_MCI_CV)/len(test_labels_MCI_CV))
    print("the f1_score_MCI is")
    print(f1_score(test_labels_MCI_CV, y_pred_MCI_CV))
        
    accr_run = np.append(accr_run, np.mean(accr_CV))
    f1s_run = np.append(f1s_run, np.mean(f1s_CV))
    accr_MCI_run = np.append(accr_MCI_run, np.sum(test_labels_MCI_CV==y_pred_MCI_CV)/len(test_labels_MCI_CV))
    f1s_MCI_run = np.append(f1s_MCI_run, f1_score(test_labels_MCI_CV, y_pred_MCI_CV))
            
print("Runs Avg Accuracies: {}".format(np.mean(accr_run)))
print("Standard Deviation: {}".format(np.std(accr_run)))
print("Runs Avg F1: {}".format(np.mean(f1s_run)))
print("Standard Deviation: {}".format(np.std(f1s_run)))
print("Runs Avg Accuracies_MCI: {}".format(np.mean(accr_MCI_run)))
print("Standard Deviation: {}".format(np.std(accr_MCI_run)))    
print("Runs Avg Accuracies_MCI: {}".format(np.mean(f1s_MCI_run)))
print("Standard Deviation: {}".format(np.std(f1s_MCI_run)))

beginning selection best number of features

 RUN: 0 ****************************** 


 Fold: 0 ************************************************** 

Accuracy: 0.733333
F1 score: 0.666667
[ 0.  1.  1.  1.  0.]
[ 0.  0.  0.  1.  1.]

 Fold: 1 ************************************************** 

Accuracy: 0.666667
F1 score: 0.545455
[ 0.  0.  1.  0.  1.]
[ 0.  0.  0.  1.  1.]

 Fold: 2 ************************************************** 

Accuracy: 0.733333
F1 score: 0.666667
[ 0.  1.  1.  1.  1.  0.  0.]
[ 1.  1.  1.  0.  1.  0.  1.]

 Fold: 3 ************************************************** 

Accuracy: 0.933333
F1 score: 0.909091
[ 0.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.]

 Fold: 4 ************************************************** 

Accuracy: 0.785714
F1 score: 0.666667
[ 0.]
[ 1.]

 Fold: 5 ************************************************** 

Accuracy: 0.928571
F1 score: 0.909091
[ 0.  0.  0.  0.  1.  1.  1.  0.]
[ 0.  0.  0.  0.  1.  1.  1.  0.]

 Fold: 6 **************************