In [1]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
import numpy as np
import pandas as pd
from pprint import pprint
from os import listdir
from os.path import isfile, join
from sklearn.model_selection import StratifiedKFold
from scipy import stats
import numpy as np
from sklearn import linear_model, svm
import re
from sklearn.metrics import roc_curve, auc,f1_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
#s = "../braindata/data_1_mor_select_100.csv"
import os          
from sklearn import linear_model, svm
from sklearn.ensemble import ExtraTreesClassifier
import xgboost as xgb

print('finished this block')

finished this block


In [2]:
os.getcwd()
os.chdir('../data/adni')
print('finished this block')

finished this block


In [3]:
dd =pd.read_csv("combine_new_biomarker_correct.csv",header=0)
print('the original training data dimension is')
print(dd.shape)
import csv

the original training data dimension is
(179, 34733)


In [4]:
with open('combine_new_biomarker_correct.csv', 'r') as f:
    d_reader = csv.DictReader(f)
    #get fieldnames from DictReader object and store in list
    headers = d_reader.fieldnames
    
data=np.array(dd)

idx_IN_columns = np.append(np.array([14,22]), np.array(range(23,data.shape[1])))

X=data[:,idx_IN_columns]
#X_biomarker=X[:,0:5]

y=data[:, 9]  
y_dxbl=data[:,10]

#ind_num_matrix=np.isnan(X_biomarker)
#ind_num_vector=np.any(ind_num_matrix,axis=1)

#X_no_nan=X[~ind_num_vector,:]
#y_no_nan=y[~ind_num_vector]
#y_dxbl_no_nan = y_dxbl[~ind_num_vector]

#X=X_no_nan
#y=y_no_nan
#y_dxbl=y_dxbl_no_nan

MCI = (y_dxbl==2)
MCI_index =[ i for i in range(0, MCI.shape[0]) if MCI[i]]


X = stats.zscore(X)

feature_num_all=[]

lr_all_feature=[]
svm_all_feature=[]
XGreg_all_feature=[]


lr_fls_feature=[]
svm_fls_feature=[]
XGB_f1s_feature=[]

base_labels= []


np.isnan(X).any()
X[np.isnan(X)] = np.median(X[~np.isnan(X)])

print("after the precoessing, the X.shape is ")
print(X.shape)
print("the y.shape is")
print(y.shape)
print("the number of MCI case is")
print(len(MCI_index))

/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:2248: RuntimeWarning: invalid value encountered in true_divide
  return (a - mns) / sstd


after the precoessing, the X.shape is 
(179, 34712)
the y.shape is
(179,)
the number of MCI case is
60


In [8]:
-  

beginning selection best number of features


 Number of Feature: 30 **************************************************************************************************** 


 RUN: 0 ****************************** 


 Fold: 0 ************************************************** 

Accuracy: 0.736842
F1 score: 0.666667
[ 0.  1.  1.  0.  0.  0.  0.]
[ 0.  0.  1.  1.  1.  0.  0.]

 Fold: 1 ************************************************** 

Accuracy: 0.578947
F1 score: 0.500000
[ 0.  1.  0.  1.  0.  0.  0.  1.]
[ 0.  0.  0.  0.  1.  1.  1.  0.]

 Fold: 2 ************************************************** 

Accuracy: 0.777778
F1 score: 0.750000
[ 0.  0.  0.  1.  0.]
[ 0.  0.  0.  1.  0.]

 Fold: 3 ************************************************** 

Accuracy: 0.833333
F1 score: 0.800000
[ 0.  0.  0.  1.  1.  0.]
[ 0.  0.  0.  0.  1.  0.]

 Fold: 4 ************************************************** 

Accuracy: 0.611111
F1 score: 0.363636
[ 0.  0.  0.  0.  1.]
[ 0.  0.  0.  0.  0.]

 Fold: 5 ***